### ISSUE TITLE
Update R scripts from the QGIS 2 collection to QGIS 3 and Processing R Provider 2.0

### ISSUE THREAD

**Issue by havatv** [qgis/QGIS-Resources#23]
This is an issue to track the progress of the updating of R scripts from the QGIS 2 online R script collection.

I will contribute, and others are welcome!

Some of the updates are quite simple - just add
`##load_vector_using_rgdal`
to avoid using `sf` for loading datasets.

The scripts from the QGIS 2 online R script collection:
- [x] [R-Geostatistics] #24
  - [x] Ordinary Kriging (renamed to Ordinary_Kriging) #24
  - [x] Variogram Modelling (renamed to Variogram_Modelling) #24
- [ ] Basic statistics
  - [ ] A-star #26
  - [x] ACP_cercle (renamed to PCA_cercle) #26
  - [x] ACP_contribution (renamed to PCA_contribution)  #26
  - [x] ACP_individus (renamed to PCA_individus) #26
  - [x] ACP_var (renamed to PCA_var)
  - [x] AFC (renamed to CoA) #26
  - [x] AFDM (renamed to FAMD) #26
  - [x] Alpha_shape #26
  - [x] ANOVA
  - [x] Autocor_spatiale (renamed to Autocor_Moran) #26
  - [x] CAH (renamed to HCA) #26
  - [x] CART #26
  - [x] Close_neighbor #26
  - [x] Density_curve
  - [x] Distance
  - [ ] Douglas-Peucker
  - [ ] Douglas-Peucker_with_choice
  - [x] Extract_points_from_line #26
  - [x] Frequency_table
  - [x] Inverse_Distance_Weigthing (renamed to Inverse_Distance_Weighting)
  - [x] Inverse_Distance_Weigthing_with_method_selection (renamed to Inverse_Distance_Weighting_with_method_selection) #26
  - [x] Kernel_density_estimation
  - [x] Kolmogrov-Smirnov_test
  - [x] Kriging #24
  - [x] Kriging_with_model_selection #24
  - [x] Multiple_Regression #24
  - [x] Polygone (renamed to Polygon_coordinates) #26
  - [x] Selection_Cp #26
  - [x] Selection_with_Bayesian_Information_Criterion #26
  - [x] Selection_with_criterion_choice #26 - needs fixing
  - [x] Selection_with_r2 #26
  - [x] Selection_with_r2_adjusted #26
  - [x] Simple_Linear_Regression #24
  - [x] Summary_statistics #26
  - [x] Tobler
- [x] ggplot
  - [x] ternaryPlots
- [x] Home range analysis
  - [x] Minimum_convex_polygon
- [x] Plots
  - [x] qqplot
- [x] Point pattern analysis
  - [x] F_function
  - [x] G_function
  - [x] Monte-Carlo_spatial_randomness
  - [x] Quadrat_analysis
  - [x] Random_sampling_grid
  - [x] Regular_sampling_grid
  - [x] Relative_distribution_(distance_covariate) #24
  - [x] Relative_distribution_(raster_covariate) #24
  - [x] Ripley_-_Rasson_spatial_domain
- [x] Raster processing
  - [x] Advanced_raster_histogram
  - [x] Raster_histogram
  - [x] raster-attribute-table
- [x] Vector processing
  - [x] barplots  (renamed to barplot)
  - [x] frequency_plot
  - [x] ggplot_scatterplot
  - [x] Histogram
  - [x] scatterplot_log
  - [x] scatterplot_types

- [x] Summarize_by_field #24
- [x] Summarize_by_two_fields #24
